-- this is a file commannds in sql
set PAGESIZE 45  --- maximum line of number per pag default is 24
SET LINESIZE 45 -- maximum number of charecter per line defult is 80
SET PAUSE ON    --set system  to pause after each page
SET PAUSE 'PRESS ANY KEY TO CONTINU'
TTITLE  CENTER '[CUSTOMER REPORT]'  -- set each title for a page
BTITLE '[END OD THE REPORT]'    -- set bottom title for a page
COLUMN CONTACTNUMBER FORMET AS TRUNC    -- this is type for column format
SELECT * FROM CUSTOMER
TTITLE OFF
BTITLE OFF
CLEAR COLUMN
SET PAGESIZE 45
SET LINESIZE 45
SET PAUSE OFF



-- this is a new file report for oracle sql commands
spool G:\PATH_OF_SPACE
set page size 34
set linesize 45
set pause on 
set pause 'press any key to contine'


-- this is a pl sql in oracle

SET SERVEROUTPUT ON     -- THIS IS USE FOR SEE A OUTPUT IN A TERMINAL OF THE COMMANDS
PROMPT ENTER COLUMN_NMAE number -- THIS IS USE FOR SHOW MESSAGE IN A TERMINAL
ACCEPT n        -- THIS IS USE FOR STORE VALUE WHICH ENTER THE USER

DECLARE
NAME EMPLOYE.NAME&TYPE;     -- THIS IS USE FOR SAME TYPE OF THE REFERENCES TABLE
DEPARTMENT EMPLOYE.DEPARTMENT&TYPE;
LOCATION EMPLOYE.LOCATION&TYPE;

BEGIN
SELECT ENAME, DPTNAME, LOCATION INTO NAME ,DEPARTMENT,  FROM EMPLOYE WHERE EID=&N;  -- THIS IS USE FOR EXTRACT DATA FROM REFERENCES TABLE
DBMS_OUTPUT.PUT_LINE ('NMAEM    :'|| NAME);     -- THIS IS USE FOR SHOW OUTPUT OF THE PROGRAM
DBMS_OUTPUT.PUT_LINE ('DEPARTNMAE :'|| DEPARTMENT);
DBMS_OUTPUT.PUT_LINE ('LOCATION :'|| LOCATION);

END;
\
SET SERVEROUTPUT OFF

-- THIS IS USE OF IF ELSE CONDITION I N PROGRAMING
SET  SERVEROUTPUT ON 
DECLARE
    A number(2) :=56;
BEGIN
    IF(A < 45) THEN
        DBMS_OUTPUT.PUT_LINE('THIS IS LESS THEN 45');
    ELSE
        DBMS_OUTPUT.PUT_LINE(' THIS IS NOT LESSTHEN 45');
    ELSE IF:
        DBMS_OUTPUT.PUT_LINE('VALUSE OF A IS :'|| A);
END;
/
SET SERVEROUTPUT OFF



    